spring:
  application:
    name: geo-metadata-service

  data:
    mongodb:
      uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB}

  rabbitmq:
    host: ${RMQ_HOST}
    port: ${RMQ_PORT}
    username: ${RMQ_USERNAME}
    password: ${RMQ_PASSWORD}
    virtual-host: ${RMQ_VHOST}
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 10
          initial-interval: 1000ms
          max-interval: 10000ms
          multiplier: 2

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"

  endpoint:
    prometheus:
      access: read_only

  prometheus:
    metrics:
      export:
        enabled: true

logback:
  logstash:
    host: ${LOGSTASH_HOST}
    port: ${LOGSTASH_PORT}
    keepAlive: ${LOGSTASH_KEEP_ALIVE}
    reconnectDelay: ${LOGSTASH_RECONNECT}