services:

  postgres:
    image: postgres:17
    container_name: geo-projects-postgres-local
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-projects-local-data:/var/lib/postgresql/data

volumes:
  postgres-projects-local-data: